#include <cuda.h>
#include <stdio.h>
#include <sys/time.h>
#include <math.h>

#define BLOCK_SIZE 16
#define NUM_PROCESSING_IMAGES 100
#define NUM_STREAMS 4 
#define NUM_RUNS 10 // Number of runs for averaging

// Fixed Full HD image size
#define IMAGE_WIDTH 1920
#define IMAGE_HEIGHT 1080

void initialData(float *ip, int size_m, int size_n){
    time_t t;
    srand((unsigned) time(&t));

    for (int i=0; i<size_m; i++){
        for (int j=0; j<size_n; j++){
            ip[i*size_n + j] = (float)(rand() & 0xFF) / 10.0f;
        }
    }
}

// from the lecture
double cpuSecond()
{
    struct timeval tp;
    gettimeofday(&tp, NULL);
    return (double)tp.tv_sec + (double)tp.tv_usec * 1.e-6;
}

// mock kernel to simulate complex image processing (target time ~1.4ms for Full HD)
__global__ void process_kernel(float *input_image, float *output_image, int size_m, int size_n) {
    
    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;

    if (row < size_m && col < size_n) {
        int idx = row * size_n + col;
        float val = input_image[idx];
        
        for (int i = 0; i < 60; i++) {
            // Simulated complex operations (generated by ChatGPT to reach target execution time)
            val = val / (val + 1.0f) * 255.0f;
            val = powf(val / 255.0f, 0.45f) * 255.0f;
            val = (val - 128.0f) * 1.1f + 128.0f;
        }
        
        // Final clamp to valid range
        val = fminf(fmaxf(val, 0.0f), 255.0f);
        
        output_image[idx] = val;
    }
}

void run_test(int task) {
    switch(task) {
        case 0: {
            printf("Task 0: Measuring execution times for Full HD images (%d x %d)\n\n", IMAGE_WIDTH, IMAGE_HEIGHT);
            
            size_t image_bytes = (size_t)IMAGE_WIDTH * IMAGE_HEIGHT * sizeof(float);
            
            float *h_image, *d_input, *d_output;
            cudaMallocHost((void **)&h_image, image_bytes);
            cudaMalloc((void **)&d_input, image_bytes);
            cudaMalloc((void **)&d_output, image_bytes);
            initialData(h_image, IMAGE_HEIGHT, IMAGE_WIDTH);
            
            // Measure Host-to-Device transfer time (average over multiple runs)
            double h2d_total = 0.0;
            for (int i = 0; i < NUM_RUNS; i++) {
                double start = cpuSecond();
                cudaMemcpy(d_input, h_image, image_bytes, cudaMemcpyHostToDevice);
                cudaDeviceSynchronize();
                h2d_total += (cpuSecond() - start) * 1000.0;
            }
            double h2d_avg = h2d_total / NUM_RUNS;
            printf("Host-to-Device transfer time: %.2f ms (avg of %d runs)\n", h2d_avg, NUM_RUNS);
            
            // Measure Kernel execution time (average over multiple runs)
            dim3 block(BLOCK_SIZE, BLOCK_SIZE);
            dim3 grid((IMAGE_WIDTH + block.x - 1) / block.x, (IMAGE_HEIGHT + block.y - 1) / block.y);
            
            // Warmup kernel launch
            process_kernel<<<grid, block>>>(d_input, d_output, IMAGE_HEIGHT, IMAGE_WIDTH);
            cudaDeviceSynchronize();
            
            double kernel_total = 0.0;
            for (int i = 0; i < NUM_RUNS; i++) {
                double start = cpuSecond();
                process_kernel<<<grid, block>>>(d_input, d_output, IMAGE_HEIGHT, IMAGE_WIDTH);
                cudaDeviceSynchronize();
                kernel_total += (cpuSecond() - start) * 1000.0;
            }
            double kernel_avg = kernel_total / NUM_RUNS;
            printf("Kernel execution time: %.2f ms (avg of %d runs)\n", kernel_avg, NUM_RUNS);
            
            // Measure Device-to-Host transfer time (average over multiple runs)
            double d2h_total = 0.0;
            for (int i = 0; i < NUM_RUNS; i++) {
                double start = cpuSecond();
                cudaMemcpy(h_image, d_output, image_bytes, cudaMemcpyDeviceToHost);
                cudaDeviceSynchronize();
                d2h_total += (cpuSecond() - start) * 1000.0;
            }
            double d2h_avg = d2h_total / NUM_RUNS;
            printf("Device-to-Host transfer time: %.2f ms (avg of %d runs)\n", d2h_avg, NUM_RUNS);
            
            printf("\nSummary: H2D=%.2fms, Kernel=%.2fms, D2H=%.2fms\n\n", h2d_avg, kernel_avg, d2h_avg);
            
            cudaFree(d_input);
            cudaFree(d_output);
            cudaFreeHost(h_image);
            break;
        }
        
        case 1: {
            printf("Task 1: Processing %d Full HD images without streaming (%d runs for averaging)\n\n", NUM_PROCESSING_IMAGES, NUM_RUNS);
            
            size_t image_bytes = (size_t)IMAGE_WIDTH * IMAGE_HEIGHT * sizeof(float);
            size_t total_bytes = NUM_PROCESSING_IMAGES * image_bytes;
            
            float *host_input_images, *host_output_images;
            cudaMallocHost((void **)&host_input_images, total_bytes);
            cudaMallocHost((void **)&host_output_images, total_bytes);
            
            float *d_input, *d_output;            
            cudaMalloc((void **)&d_input, image_bytes);
            cudaMalloc((void **)&d_output, image_bytes);
            
            for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {
                initialData(&host_input_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], IMAGE_HEIGHT, IMAGE_WIDTH);
            }
            
            dim3 block(BLOCK_SIZE, BLOCK_SIZE);
            dim3 grid((IMAGE_WIDTH + block.x - 1) / block.x, (IMAGE_HEIGHT + block.y - 1) / block.y);
            
            double total_elapsed = 0.0;
            for (int run = 0; run < NUM_RUNS; run++) {
                double start = cpuSecond();
                
                // Process each image SEQUENTIALLY: H2D -> Kernel -> D2H -> sync, then next image
                for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {                  
                    cudaMemcpy(d_input, 
                              &host_input_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], 
                              image_bytes, cudaMemcpyHostToDevice);
                    cudaDeviceSynchronize(); 
               
                    process_kernel<<<grid, block>>>(d_input, d_output, IMAGE_HEIGHT, IMAGE_WIDTH);
                    cudaDeviceSynchronize();  
                    
                    cudaMemcpy(&host_output_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], 
                              d_output, 
                              image_bytes, cudaMemcpyDeviceToHost);
                    cudaDeviceSynchronize();  
                }
                
                cudaDeviceSynchronize();
                double elapsed = (cpuSecond() - start) * 1000.0;
                total_elapsed += elapsed;
                printf("  Run %d: %.2f ms\n", run + 1, elapsed);
            }
            
            double avg_elapsed = total_elapsed / NUM_RUNS;
            printf("\nAverage time (no streaming): %.2f ms\n\n", avg_elapsed);
            
            cudaFree(d_input);
            cudaFree(d_output);
            cudaFreeHost(host_input_images);
            cudaFreeHost(host_output_images);
            break;
        }
        
        case 2: {
            printf("Task 2: Processing %d Full HD images WITH streaming (%d streams, %d runs for averaging)\n\n", 
                   NUM_PROCESSING_IMAGES, NUM_STREAMS, NUM_RUNS);
            
            size_t image_bytes = (size_t)IMAGE_WIDTH * IMAGE_HEIGHT * sizeof(float);
            size_t total_bytes = NUM_PROCESSING_IMAGES * image_bytes;
            
            float *host_input_images, *host_output_images;
            cudaMallocHost((void **)&host_input_images, total_bytes);
            cudaMallocHost((void **)&host_output_images, total_bytes);
            
            for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {
                initialData(&host_input_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], IMAGE_HEIGHT, IMAGE_WIDTH);
            }
            
            // Create streams
            cudaStream_t streams[NUM_STREAMS];
            for (int i = 0; i < NUM_STREAMS; i++) {
                cudaStreamCreate(&streams[i]);
            }
            
            // Allocate device memory for all images (partitioned by stream)
            float *d_input[NUM_STREAMS], *d_output[NUM_STREAMS];
            int images_per_stream = (NUM_PROCESSING_IMAGES + NUM_STREAMS - 1) / NUM_STREAMS;
            for (int i = 0; i < NUM_STREAMS; i++) {
                cudaMalloc((void **)&d_input[i], images_per_stream * image_bytes);
                cudaMalloc((void **)&d_output[i], images_per_stream * image_bytes);
            }
            
            dim3 block(BLOCK_SIZE, BLOCK_SIZE);
            dim3 grid((IMAGE_WIDTH + block.x - 1) / block.x, (IMAGE_HEIGHT + block.y - 1) / block.y);
            
            double total_elapsed = 0.0;
            for (int run = 0; run < NUM_RUNS; run++) {
                double start = cpuSecond();
                                
                for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {
                    int stream_idx = i % NUM_STREAMS;
                    int local_idx = i / NUM_STREAMS;  // Index within this stream's buffer
                    
                    cudaMemcpyAsync(&d_input[stream_idx][local_idx * IMAGE_WIDTH * IMAGE_HEIGHT], 
                                   &host_input_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], 
                                   image_bytes, cudaMemcpyHostToDevice, streams[stream_idx]);
                }
                
                for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {
                    int stream_idx = i % NUM_STREAMS;
                    int local_idx = i / NUM_STREAMS;
                    
                    process_kernel<<<grid, block, 0, streams[stream_idx]>>>(
                        &d_input[stream_idx][local_idx * IMAGE_WIDTH * IMAGE_HEIGHT], 
                        &d_output[stream_idx][local_idx * IMAGE_WIDTH * IMAGE_HEIGHT], 
                        IMAGE_HEIGHT, IMAGE_WIDTH);
                }
                
                for (int i = 0; i < NUM_PROCESSING_IMAGES; i++) {
                    int stream_idx = i % NUM_STREAMS;
                    int local_idx = i / NUM_STREAMS;
                    
                    cudaMemcpyAsync(&host_output_images[i * IMAGE_WIDTH * IMAGE_HEIGHT], 
                                   &d_output[stream_idx][local_idx * IMAGE_WIDTH * IMAGE_HEIGHT], 
                                   image_bytes, cudaMemcpyDeviceToHost, streams[stream_idx]);
                }
                
                cudaDeviceSynchronize();
                
                double elapsed = (cpuSecond() - start) * 1000.0;
                if (run > 0) total_elapsed += elapsed;  // Skip first run (warmup)
                printf("  Run %d: %.2f ms%s\n", run + 1, elapsed, run == 0 ? " (warmup)" : "");
            }
            
            double avg_elapsed = total_elapsed / (NUM_RUNS - 1);
            printf("\nAverage time WITH streaming: %.2f ms (excluding warmup)\n", avg_elapsed);
            
            // Cleanup
            for (int i = 0; i < NUM_STREAMS; i++) {
                cudaStreamDestroy(streams[i]);
                cudaFree(d_input[i]);
                cudaFree(d_output[i]);
            }
            cudaFreeHost(host_input_images);
            cudaFreeHost(host_output_images);
            break;
        }
        
        default: {
            printf("Invalid task number. Please choose a valid task.\n");
            break;
        }
    }
    return;
}

int main() {
    run_test(0);
    run_test(1);
    run_test(2);
    
    return 0;
}
